# Generated by Django 2.1.5 on 2019-02-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=60)),
                ('birthdate', models.DateField()),
                ('pnumber', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=50)),
            ],
        ),
    ]
