# Generated by Django 2.1.5 on 2019-02-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mmovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
        ),
    ]
