# Generated by Django 2.1.5 on 2019-02-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_index'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmovies',
            name='fname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers'),
        ),
        migrations.AlterField(
            model_name='mmovies',
            name='genre',
            field=models.CharField(choices=[('AC', 'Action'), ('TH', 'Thriller'), ('RM', 'Romance'), ('Co', 'Comedy')], max_length=60),
        ),
    ]
